apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: echo
  labels:
    app: echo-app
spec:
  # Define number of working PODs for this application
  replicas: 1
  # Selector says which PODs this deployment should manage
  selector:
    matchLabels:
      app: echo-app
  # Template (template) describes how each created POD should look like
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: echo-app
        image: alpine
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache nmap-ncat
          echo "Echo server started..."
          ncat -lk -p 8080 -c "while read msg; do \
            echo \"\$msg\" | nc -w 2 db-service 5432 >/dev/null 2>&1 & \
            ts=\$(date '+%Y-%m-%d %H:%M:%S'); \
            echo \"Received: '\$msg' [Pod IP: \$MY_POD_IP] [Time: \$ts]\"; \
          done"
        ports:
        - containerPort: 8080

---
# Service for the application will remain unchanged – thanks to the label "app: echo-app"
# it will automatically detect the pod created by the Deployment.
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: echo
spec:
  selector:
    app: echo-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
