apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-deployment
  namespace: echo
  labels:
    app: echo-app
spec:
  # Define number of working PODs for this application
  replicas: 1
  # Selector says which PODs this deployment should manage
  selector:
    matchLabels:
      app: echo-app
  # Template (template) describes how each created POD should look like
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
      - name: echo-app
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache netcat-openbsd
          echo "Echo server started from Deployment..."
          while true; do
            MSG=$(nc -l -p 8080)
            if [ ! -z "$MSG" ]; then
              echo "Log: $MSG" | nc db-service 5432
              echo "ECHO: $MSG"
            fi
          done
        ports:
        - containerPort: 8080

---
# Service for the application will remain unchanged – thanks to the label "app: echo-app"
# it will automatically detect the pod created by the Deployment.
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: echo
spec:
  selector:
    app: echo-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
